site_name: Introduction to statistics with R
nav:
    - Home: index.md
    - Precourse preparation: precourse.md
    - Course schedule: course_schedule.md
    - Day 1: day1.md
    - Day 2: day2.md
    - Day 3: day3.md
    - Advanced topics: day4.md
    - Exam: exam.md
    - Useful links: links.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
	features: 
		- content.code.copy

# Repository
repo_name: sib-swiss/Introduction-to-statistics-with-R
repo_url: https://github.com/sib-swiss/Introduction-to-statistics-with-R

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
